/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use Scala 2.13 in our library project
    implementation("org.scala-lang:scala-library:2.11.12")
    implementation("org.apache.spark:spark-core_2.11:2.4.8")
    implementation("org.apache.spark:spark-sql_2.11:2.4.8")
    implementation("org.apache.spark:spark-streaming_2.11:2.4.8")
    implementation("org.apache.phoenix:phoenix-spark:4.14.2-HBase-1.4")
    implementation("com.typesafe:config:1.4.2")
    implementation("org.postgresql:postgresql:42.2.5")



    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")
}